#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

function reset_color_if_not_VIM {
	#autocmd events in plugin/bspwm_border_color.vim will handle case where window is VIM
	node_id=$(echo $1 | grep -oE '[^ ]+$')
	node_name=$(xtitle $node_id)


	if [[ $node_name != *"ᴠɪᴍ"* ]]; then
		$SCRIPTPATH/reset $2
	fi
}

bspc subscribe node_focus | while read -r line; do reset_color_if_not_VIM "$line" $1; done &
