#!/bin/bash

#Only start listener if it isn't already running
if ! ps -ef | grep "bin/bash.*bspwm_border_listener" | grep -v "grep" > /dev/null
then
	$HOME/.vim/bundle/bspwm_border_color/bspwm_border_listener & disown
fi
