#!/bin/bash

#this script is called by the autocmd events in ~/.vimrc
if [ $1 = "i" ]; then
	bspc config focused_border_color ${BSPWM_VIM_INSERT:-'#e21855'} #red
else
	bspc config focused_border_color ${BSPWM_VIM_NORMAL:-'#2cba1f'} #green
fi
bspc config borderless_monocle "false"
